application:
  developMode: true
  mysql:
    ip: 127.0.0.1
    port: 3306
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    database: zt-eweb
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://${application.mysql.ip}:${application.mysql.port}/${application.mysql.database}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      #      id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
      #      id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      #      id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      banner: false # 关闭控制台的 Banner 打印
  configuration:
    # 虽然默认为 true ，但是还是显示去指定下。
    map-underscore-to-camel-case: true
    # 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zt.eweb.modular.**.dal
# mybatis xml文件热加载配置
mybatis-xml-reload:
  # 是否开启 xml 热更新，true开启，false不开启，默认为false
  enabled: true
  # xml文件路径，可以填写多个，逗号分隔。如果想将xml文件放在指定目录而不是jar包内，可以用file前缀指定本地目录，例如 file:/c/mapper/*.xml
  # eg: `classpath:mapper/**/*Mapper.xml,file:/c/mapper/*.xml`
  mapper-locations: classpath:mapper/**/*Mapper.xml

logging:
  level:
    ROOT: INFO
    com.zt.eweb: ${logging.level.ROOT}
  file:
    path: logs
    info-file-name: info
    error-file-name: error
springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn
# actuator
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "threaddump", "logfile" ]
  endpoint:
    health:
      show-details: when_authorized
  info:
    git:
      mode: full
  health:
    # 生成环境的话注意安全问题
    # 生成环境的话注意安全问题
    show-details: always
    # 启用或禁用k8s健康检查
    probes:
      enabled: true
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    enabled: false # http://micrometer.io/ is disabled by default, as we use http://metrics.dropwizard.io/ instead

