logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework:
        web: trace
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      #      id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
      #      id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      #      id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      banner: false # 关闭控制台的 Banner 打印
  configuration:
    # 虽然默认为 true ，但是还是显示去指定下。
    map-underscore-to-camel-case: true
    # 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  error:
    include-stacktrace: always
spring:
  datasource:
    druid:
      # ===========监控配置===========
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/zt-eweb?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            # 初始化连接大小
            initial-size: 10
            #最大连接池数量
            max-active: 1000
            # 最小连接池数量
            min-idle: 3
            # 配置获取连接等待超时的时间 单位毫秒
            max-wait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            # 测试连接
            validation-query: select
            # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
            test-while-idle: true
            # 获取连接时执行检测，建议关闭，影响性能
            test-on-borrow: false
            # 归还连接时执行检测，建议关闭，影响性能
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            #      配置监控统计拦截器 防火墙 日志配置
            #      stat监控数据库性能
            #      wall  用于防火墙
            #      日志
            #      slf4j logback
            #      log4j
            #      log4j2
            # 配置多个英文逗号分隔
            max-pool-prepared-statement-per-connection-size: 20
            # 合并多个DruidDataSource的监控数据
            use-global-data-source-stat: true
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 SQL优化
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
            # ===========监控配置===========
            # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
            filters: stat,wall,slf4j
            proxy-filters: slowSqlTestFilter
        slave:
          url: jdbc:mysql://127.0.0.1:3306/zt-eweb?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            # 初始化连接大小
            initial-size: 5
            #最大连接池数量
            max-active: 20
            # 最小连接池数量
            min-idle: 3
            # 配置获取连接等待超时的时间 单位毫秒
            max-wait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            # 测试连接
            validation-query: select
            # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
            test-while-idle: true
            # 获取连接时执行检测，建议关闭，影响性能
            test-on-borrow: false
            # 归还连接时执行检测，建议关闭，影响性能
            test-on-return: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            #      配置监控统计拦截器 防火墙 日志配置
            #      stat监控数据库性能
            #      wall  用于防火墙
            #      日志 slf4j logback
            #      log4j
            #      log4j2
            # 配置多个英文逗号分隔
            max-pool-prepared-statement-per-connection-size: 20
            # 合并多个DruidDataSource的监控数据
            use-global-data-source-stat: true
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 SQL优化
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
            filters: stat,wall,slf4j