server:
  port: 8888
spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类
  profiles:
    active: @spring.active@
  application:
    name: zt-eweb-lite
  aop:
    auto: true
  # Jackson 配置项
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true # 设置 LocalDateTime 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean
  servlet:
    # 文件上传相关配置项
    multipart:
      # 单个文件大小
      max-file-size: "100MB"
      # 设置总上传的文件大小
      max-request-size: "1000MB"
  redis:
    password: 123456
    port: 6379
    host: localhost

easy:
  # web防火墙配置
  waf:
    sql-enabled: true
    xss-enabled: true
    excludes: /flow/*,/sys/nginx/*,/ureport/*,/sys/menu/*
autolog:
  app-name: ZTEweb